name: Generate Forgetting Curve

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate_curve:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Checkout the external repository
      run: |
        git clone https://github.com/QingzeHu/LeetCurve.git LeetCurve
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Forgetting Curve
      run: |
        python scripts/generate_forgetting_curve.py
